[project]
name = "ai-market-agent-vaia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.0",
    "openai>=2.6.1",
    "pgvector>=0.4.1",
    "tiktoken>=0.12.0",
]
